function export_cps_v10_reference( ...
        outputRoot, runFmu, allowOverwrite)
%EXPORT_CPS_V10_REFERENCE Export the two T1 MATLAB reference scenarios.
%
%   export_cps_v10_reference()
%   regenerates the dedicated-resource and shared-cloud scheduler traces,
%   verifies them against the checked-in MATLAB archives, runs the Simulink
%   model, and exports selected FMU outputs.
%
%   export_cps_v10_reference("", false)
%   performs the scheduler/archive export without running Simulink. This is
%   useful when the Windows FMU or Simulink is unavailable.
%
%   export_cps_v10_reference(outputRoot, runFmu, true)
%   explicitly permits replacement of existing generated artifacts. Golden
%   artifacts must not be replaced without documenting the reason in review.

    arguments
        outputRoot (1, 1) string = ""
        runFmu (1, 1) logical = true
        allowOverwrite (1, 1) logical = false
    end

    simulinkDir = string(fileparts(mfilename("fullpath")));
    repoRoot = string(fileparts(simulinkDir));

    if strlength(outputRoot) == 0
        outputRoot = fullfile( ...
            repoRoot, "experiments", "bosch_v10_reference");
    end

    if runFmu && ~ispc
        error( ...
            "The checked-in FMU contains a Windows binary. " + ...
            "Run the full export on Windows, or pass runFmu=false.");
    end

    timingDir = fullfile(simulinkDir, "timing");
    addpath(timingDir);
    pathCleanup = onCleanup(@() rmpath(timingDir));

    [t, plantInputData, Ts, Tstop] = loadTrajectory(repoRoot);
    stopTick = round(Tstop / Ts);

    assert(numel(t) == stopTick + 1, ...
        "Trajectory length does not match the scheduler horizon.");

    previousRandomState = rng;
    randomCleanup = onCleanup(@() rng(previousRandomState));
    rng(0, "twister");

    mappingModes = ["dedicated", "cloud1"];
    scenarioNames = ["dedicated", "shared_cloud"];
    dedicatedTrigger = [];

    for scenarioIndex = 1:numel(mappingModes)
        mappingMode = mappingModes(scenarioIndex);
        scenarioName = scenarioNames(scenarioIndex);

        [cfg, tasks] = define_cps_v10_taskset(mappingMode);

        assert(abs(cfg.sampleTimeSec - Ts) < 1e-15, ...
            "Scheduler and trajectory sample times differ.");

        jobsInput = generate_periodic_jobs(tasks, stopTick);

        [jobsScheduled, scheduleScheduled] = ...
            simulate_fp_resources( ...
                cfg, tasks, jobsInput, stopTick);

        [triggerScheduled, networkLogScheduled] = ...
            encode_fmu_triggers( ...
                cfg, tasks, jobsScheduled, stopTick);

        verifyCheckedInArchive( ...
            simulinkDir, ...
            mappingMode, ...
            cfg, ...
            tasks, ...
            jobsScheduled, ...
            scheduleScheduled, ...
            triggerScheduled, ...
            networkLogScheduled);

        if mappingMode == "dedicated"
            dedicatedTrigger = triggerScheduled;
        end

        assert(~isempty(dedicatedTrigger), ...
            "The dedicated scenario must be processed first.");

        differingTriggerEntries = nnz(xor( ...
            triggerScheduled, dedicatedTrigger));

        validateExpectedCounts( ...
            mappingMode, ...
            jobsScheduled, ...
            scheduleScheduled, ...
            triggerScheduled, ...
            networkLogScheduled, ...
            differingTriggerEntries);

        triggerEvents = makeTriggerEventTable( ...
            triggerScheduled, cfg.sampleTimeSec);

        selectedJobColumns = [ ...
            "taskId", ...
            "taskName", ...
            "jobId", ...
            "resource", ...
            "priority", ...
            "releaseTick", ...
            "absoluteDeadlineTick", ...
            "executionTicks", ...
            "firstStartTick", ...
            "finishTick", ...
            "preemptionCount", ...
            "deadlineMiss"];

        jobsExport = jobsScheduled(:, selectedJobColumns);

        fmuOutputs = table();
        if runFmu
            fmuOutputs = runModelAndCollectOutputs( ...
                repoRoot, ...
                t, ...
                plantInputData, ...
                triggerScheduled, ...
                Tstop, ...
                mappingMode);
        end

        summary = makeSummaryTable( ...
            jobsScheduled, ...
            scheduleScheduled, ...
            triggerScheduled, ...
            networkLogScheduled, ...
            differingTriggerEntries, ...
            runFmu);

        scenarioDir = fullfile(outputRoot, scenarioName);
        writeScenarioArtifacts( ...
            scenarioDir, ...
            allowOverwrite, ...
            tasks, ...
            jobsExport, ...
            scheduleScheduled.eventLog, ...
            networkLogScheduled, ...
            triggerEvents, ...
            summary, ...
            fmuOutputs, ...
            runFmu);

        fprintf( ...
            "Exported %s reference artifacts to:\n%s\n", ...
            mappingMode, scenarioDir);
    end

    clear pathCleanup randomCleanup;
end


function [t, plantInputData, Ts, Tstop] = loadTrajectory(repoRoot)
%LOADTRAJECTORY Load and validate the first 15 seconds of example_v_10.

    dataDir = fullfile( ...
        repoRoot, "examples", "example_v_10");

    Ts = 1e-4;
    Tstop = 15.0;

    timeAll = readmatrix(fullfile(dataDir, "time_vector.csv"));
    ff0All = readmatrix(fullfile( ...
        dataDir, "feedforward_sequence_0.csv"));
    ff1All = readmatrix(fullfile( ...
        dataDir, "feedforward_sequence_1.csv"));
    velocityAll = readmatrix(fullfile(dataDir, "velocity.csv"));

    timeAll = timeAll(:);
    ff0All = ff0All(:);
    ff1All = ff1All(:);
    velocityAll = velocityAll(:);

    numRows = min([ ...
        numel(timeAll), ...
        numel(ff0All), ...
        numel(ff1All), ...
        numel(velocityAll)]);

    rawData = [ ...
        timeAll(1:numRows), ...
        ff0All(1:numRows), ...
        ff1All(1:numRows), ...
        velocityAll(1:numRows)];

    rawData = rawData(all(isfinite(rawData), 2), :);

    if isempty(rawData)
        error("The example_v_10 trajectory contains no valid samples.");
    end

    if abs(rawData(1, 1)) > 1e-12
        error("The example_v_10 time vector does not begin at zero.");
    end

    numCheckSamples = min(size(rawData, 1), 10001);
    observedTs = median(diff(rawData(1:numCheckSamples, 1)));

    if abs(observedTs - Ts) > 1e-10
        error("Unexpected trajectory step: %.12g seconds.", observedTs);
    end

    keep = rawData(:, 1) <= Tstop + Ts / 2;
    selectedData = rawData(keep, :);

    t = selectedData(:, 1);
    plantInputData = selectedData(:, 2:4);
end


function verifyCheckedInArchive( ...
        simulinkDir, mappingMode, cfg, tasks, jobsScheduled, ...
        scheduleScheduled, triggerScheduled, networkLogScheduled)
%VERIFYCHECKEDINARCHIVE Compare regenerated timing data with the oracle.

    archiveFile = fullfile( ...
        simulinkDir, ...
        sprintf("cps_v10_scheduled_%s.mat", mappingMode));

    if ~isfile(archiveFile)
        error("Checked-in reference archive not found: %s", archiveFile);
    end

    archived = load( ...
        archiveFile, ...
        "cfg", ...
        "tasks", ...
        "jobsScheduled", ...
        "scheduleScheduled", ...
        "triggerScheduled", ...
        "networkLogScheduled");

    assert(isequaln(cfg, archived.cfg), ...
        "Regenerated cfg differs from the checked-in archive.");
    assert(isequaln(tasks, archived.tasks), ...
        "Regenerated tasks differ from the checked-in archive.");
    assert(isequaln(jobsScheduled, archived.jobsScheduled), ...
        "Regenerated jobs differ from the checked-in archive.");
    assert(isequaln( ...
            scheduleScheduled.eventLog, ...
            archived.scheduleScheduled.eventLog), ...
        "Regenerated scheduler events differ from the checked-in archive.");
    assert(isequaln( ...
            scheduleScheduled.executionJobRow, ...
            archived.scheduleScheduled.executionJobRow), ...
        "Regenerated execution timeline differs from the archive.");
    assert(isequaln(triggerScheduled, archived.triggerScheduled), ...
        "Regenerated triggers differ from the checked-in archive.");
    assert(isequaln( ...
            networkLogScheduled, ...
            archived.networkLogScheduled), ...
        "Regenerated network events differ from the checked-in archive.");
end


function validateExpectedCounts( ...
        mappingMode, jobs, schedule, trigger, networkLog, ...
        differingTriggerEntries)
%VALIDATEEXPECTEDCOUNTS Detect accidental changes to the T1 baseline.

    expected = struct();
    expected.jobs = 7256;
    expected.releases = 7256;
    expected.finishes = 7250;
    expected.resumes = 0;
    expected.preemptions = 0;
    expected.deadlineMisses = 0;
    expected.networkPackets = 3750;
    expected.networkSendsInTrace = 3750;
    expected.networkReceivesInTrace = 3749;

    switch mappingMode
        case "dedicated"
            expected.starts = 7256;
            expected.schedulerEvents = 21762;
            expected.triggerEntries = 22005;
            expected.differingTriggerEntries = 0;

        case "cloud1"
            expected.starts = 7253;
            expected.schedulerEvents = 21759;
            expected.triggerEntries = 22002;
            expected.differingTriggerEntries = 12003;

        otherwise
            error("No T1 expected counts for mapping '%s'.", mappingMode);
    end

    assert(height(jobs) == expected.jobs);
    assert(height(schedule.eventLog) == expected.schedulerEvents);
    assert(height(schedule.releaseEvents) == expected.releases);
    assert(height(schedule.startEvents) == expected.starts);
    assert(height(schedule.resumeEvents) == expected.resumes);
    assert(height(schedule.preemptionEvents) == expected.preemptions);
    assert(height(schedule.finishEvents) == expected.finishes);
    assert(height(schedule.deadlineMissEvents) == expected.deadlineMisses);
    assert(nnz(trigger) == expected.triggerEntries);
    assert(height(networkLog) == expected.networkPackets);
    assert(nnz(networkLog.sendInTrace) == ...
        expected.networkSendsInTrace);
    assert(nnz(networkLog.receiveInTrace) == ...
        expected.networkReceivesInTrace);
    assert(differingTriggerEntries == ...
        expected.differingTriggerEntries);
end


function triggerEvents = makeTriggerEventTable(trigger, sampleTimeSec)
%MAKETRIGGEREVENTTABLE Convert the Boolean matrix to sparse event rows.

    triggerNames = [ ...
        "sensor_activated", ...
        "sensor_finished", ...
        "uplink_sent", ...
        "uplink_received", ...
        "estimator_activated", ...
        "estimator_finished", ...
        "controller_activated", ...
        "controller_finished", ...
        "feedforward_activated", ...
        "feedforward_finished", ...
        "merger_activated", ...
        "merger_finished", ...
        "downlink_sent", ...
        "downlink_received", ...
        "actuator_activated", ...
        "actuator_finished"];

    [rowIndex, triggerColumn] = find(trigger);
    eventTick = rowIndex - 1;
    eventTimeSec = eventTick .* sampleTimeSec;
    triggerName = triggerNames(triggerColumn);
    triggerName = triggerName(:);

    triggerEvents = table( ...
        eventTick, ...
        eventTimeSec, ...
        triggerColumn, ...
        triggerName);

    triggerEvents = sortrows( ...
        triggerEvents, ["eventTick", "triggerColumn"]);
end


function fmuOutputs = runModelAndCollectOutputs( ...
        repoRoot, t, plantInputData, trigger, Tstop, mappingMode)
%RUNMODELANDCOLLECTOUTPUTS Run Simulink and collect selected FMU signals.

    modelName = "cps_single_vehicle_v10";
    modelFile = fullfile( ...
        repoRoot, "simulink", modelName + ".slx");

    originalDirectory = string(pwd);
    directoryCleanup = onCleanup(@() cd(originalDirectory));
    cd(repoRoot);

    load_system(modelFile);
    modelCleanup = onCleanup(@() close_system(modelName, 0));

    triggerTs = timeseries(logical(trigger), t);
    triggerTs.Name = sprintf( ...
        "CPS scheduler triggers: %s", mappingMode);

    plantInputsTs = timeseries(plantInputData, t);
    plantInputsTs.Name = "CPS trajectory inputs";

    simulationInput = Simulink.SimulationInput(modelName);
    simulationInput = simulationInput.setVariable( ...
        "trigger_ts", triggerTs);
    simulationInput = simulationInput.setVariable( ...
        "plant_inputs_ts", plantInputsTs);
    simulationInput = simulationInput.setModelParameter( ...
        "StopTime", sprintf("%.17g", Tstop));

    simulationOutput = sim(simulationInput);

    selectedSignals = [ ...
        "lateral_error", ...
        "actuator_command", ...
        "rolling_real", ...
        "rolling_remote", ...
        "violation_counter", ...
        "critical_section"];

    fmuOutputs = table();
    referenceTime = [];

    for signalIndex = 1:numel(selectedSignals)
        signalName = selectedSignals(signalIndex);
        signalValue = simulationOutput.get(char(signalName));

        if ~isa(signalValue, "timeseries")
            error("FMU output '%s' is not a timeseries.", signalName);
        end

        signalTime = signalValue.Time(:);
        signalData = squeeze(signalValue.Data);
        signalData = signalData(:);

        if numel(signalTime) ~= numel(signalData)
            error("FMU output '%s' is not scalar-valued.", signalName);
        end

        if isempty(referenceTime)
            referenceTime = signalTime;
            fmuOutputs.time_sec = referenceTime;
        elseif ~isequal(referenceTime, signalTime)
            error("FMU output '%s' uses a different time base.", signalName);
        end

        fmuOutputs.(char(signalName)) = signalData;
    end

    clear modelCleanup directoryCleanup;
end


function summary = makeSummaryTable( ...
        jobs, schedule, trigger, networkLog, ...
        differingTriggerEntries, fmuExecuted)
%MAKESUMMARYTABLE Produce machine-readable counts for review.

    metric = [ ...
        "jobs"; ...
        "scheduler_events"; ...
        "release_events"; ...
        "start_events"; ...
        "resume_events"; ...
        "preemption_events"; ...
        "finish_events"; ...
        "deadline_miss_events"; ...
        "true_trigger_entries"; ...
        "trigger_differences_from_dedicated"; ...
        "network_packets"; ...
        "network_sends_in_trace"; ...
        "network_receives_in_trace"; ...
        "fmu_executed"];

    value = [ ...
        height(jobs); ...
        height(schedule.eventLog); ...
        height(schedule.releaseEvents); ...
        height(schedule.startEvents); ...
        height(schedule.resumeEvents); ...
        height(schedule.preemptionEvents); ...
        height(schedule.finishEvents); ...
        height(schedule.deadlineMissEvents); ...
        nnz(trigger); ...
        differingTriggerEntries; ...
        height(networkLog); ...
        nnz(networkLog.sendInTrace); ...
        nnz(networkLog.receiveInTrace); ...
        double(fmuExecuted)];

    summary = table(metric, value);
end


function writeScenarioArtifacts( ...
        scenarioDir, allowOverwrite, tasks, jobs, schedulerEvents, ...
        networkEvents, triggerEvents, summary, fmuOutputs, runFmu)
%WRITESCENARIOARTIFACTS Write one scenario without silent replacement.

    artifactNames = [ ...
        "tasks.csv", ...
        "jobs.csv", ...
        "scheduler_events.csv", ...
        "network_events.csv", ...
        "trigger_events.csv", ...
        "summary.csv"];

    if runFmu
        artifactNames(end + 1) = "fmu_outputs.csv";
    end

    if ~isfolder(scenarioDir)
        mkdir(scenarioDir);
    end

    for artifactIndex = 1:numel(artifactNames)
        artifactFile = fullfile( ...
            scenarioDir, artifactNames(artifactIndex));

        if isfile(artifactFile) && ~allowOverwrite
            error( ...
                "Refusing to replace golden artifact: %s. " + ...
                "Pass allowOverwrite=true only after documenting " + ...
                "the regeneration reason.", ...
                artifactFile);
        end
    end

    writetable(tasks, fullfile(scenarioDir, "tasks.csv"));
    writetable(jobs, fullfile(scenarioDir, "jobs.csv"));
    writetable( ...
        schedulerEvents, ...
        fullfile(scenarioDir, "scheduler_events.csv"));
    writetable( ...
        networkEvents, ...
        fullfile(scenarioDir, "network_events.csv"));
    writetable( ...
        triggerEvents, ...
        fullfile(scenarioDir, "trigger_events.csv"));
    writetable(summary, fullfile(scenarioDir, "summary.csv"));

    if runFmu
        writetable( ...
            fmuOutputs, ...
            fullfile(scenarioDir, "fmu_outputs.csv"));
    end
end
