%% Prepare scheduler-derived inputs for the CPS Challenge FMU
%
% This script:
%   1. Uses the existing prepare_cps_v10.m script to load the trajectory.
%   2. Generates jobs from the explicit task model.
%   3. Simulates fixed-priority scheduling.
%   4. Replaces the manually generated trigger_ts with scheduler-derived
%      task and network events.
%
% Change mappingMode below between:
%
%   "dedicated"  - one virtual processor per task; compatibility baseline
%   "cloud1"     - four cloud tasks share one preemptive processor

%% Load the original trajectory and reference trigger trace

% prepare_cps_v10.m begins with clearvars, so call it before defining
% this script's scheduling variables.
run("prepare_cps_v10.m");

% Preserve the manually constructed trigger trace for comparison.
triggerManual = logical(trigger_ts.Data);

%% Scheduler configuration

mappingMode = "dedicated";  % "dedicated", "cloud1"

timingDir = fullfile(repoRoot, "simulink", "timing");
addpath(timingDir);

[cfg, tasks] = define_cps_v10_taskset(mappingMode);

assert(abs(cfg.sampleTimeSec - Ts) < 1e-15, ...
    "Scheduler and Simulink sample times differ.");

stopTick = round(Tstop / cfg.sampleTimeSec);

assert(numel(t) == stopTick + 1, ...
    "Trajectory length does not match the scheduler horizon.");

%% Generate and schedule periodic jobs

jobsInput = generate_periodic_jobs(tasks, stopTick);

[jobsScheduled, scheduleScheduled] = ...
    simulate_fp_resources( ...
        cfg, ...
        tasks, ...
        jobsInput, ...
        stopTick);

%% Generate task and network triggers

[triggerScheduled, networkLogScheduled] = ...
    encode_fmu_triggers( ...
        cfg, ...
        tasks, ...
        jobsScheduled, ...
        stopTick);

assert(isequal(size(triggerScheduled), size(triggerManual)), ...
    "Scheduled and reference trigger matrices have different sizes.");

%% Check the selected mapping

numDifferentTriggerEntries = nnz( ...
    xor(triggerScheduled, triggerManual));

fprintf("\nMapping mode: %s\n", mappingMode);
fprintf("Trigger entries differing from manual trace: %d\n", ...
    numDifferentTriggerEntries);

switch mappingMode
    case "dedicated"
        assert(numDifferentTriggerEntries == 0, ...
            "Dedicated scheduling should reproduce the reference trace.");

    case "cloud1"
        assert(numDifferentTriggerEntries > 0, ...
            "Shared-cloud scheduling unexpectedly reproduced the " + ...
            "dedicated trace.");
end

%% Check scheduler results

numPreemptions = height(scheduleScheduled.preemptionEvents);
numDeadlineMisses = height(scheduleScheduled.deadlineMissEvents);

fprintf("Preemptions: %d\n", numPreemptions);
fprintf("Deadline misses: %d\n", numDeadlineMisses);

% The nominal one-vehicle baseline should remain schedulable.
assert(numDeadlineMisses == 0, ...
    "The nominal one-vehicle baseline should have no deadline misses.");

%% Construct the Simulink FMU input

trigger_ts = timeseries(logical(triggerScheduled), t);

trigger_ts.Name = sprintf( ...
    "CPS scheduler triggers: %s", mappingMode);

% plant_inputs_ts was created by prepare_cps_v10.m and is unchanged.

%% Print per-task timing statistics

fprintf("\nPer-task timing results:\n");
fprintf("%-13s %10s %10s %10s %10s\n", ...
    "Task", ...
    "Jobs", ...
    "MeanWait", ...
    "MaxWait", ...
    "MaxResp");

fprintf("%-13s %10s %10s %10s %10s\n", ...
    "", ...
    "", ...
    "(ms)", ...
    "(ms)", ...
    "(ms)");

for taskIndex = 1:height(tasks)
    taskRows = ...
        jobsScheduled.taskId == tasks.taskId(taskIndex) & ...
        isfinite(jobsScheduled.firstStartTick);

    completedRows = ...
        taskRows & ...
        isfinite(jobsScheduled.finishTick);

    waitingTicks = ...
        jobsScheduled.firstStartTick(taskRows) - ...
        jobsScheduled.releaseTick(taskRows);

    responseTicks = ...
        jobsScheduled.finishTick(completedRows) - ...
        jobsScheduled.releaseTick(completedRows);

    meanWaitingMs = ...
        mean(waitingTicks) * cfg.sampleTimeSec * 1e3;

    maxWaitingMs = ...
        max(waitingTicks) * cfg.sampleTimeSec * 1e3;

    maxResponseMs = ...
        max(responseTicks) * cfg.sampleTimeSec * 1e3;

    fprintf("%-13s %10d %10.3f %10.3f %10.3f\n", ...
        tasks.name(taskIndex), ...
        nnz(taskRows), ...
        meanWaitingMs, ...
        maxWaitingMs, ...
        maxResponseMs);
end

%% Show resource utilization

fprintf("\nResource utilization:\n");
disp(scheduleScheduled.resourceTable);

%% Save reproducible scheduler and FMU inputs

outputFile = fullfile( ...
    repoRoot, ...
    "simulink", ...
    sprintf("cps_v10_scheduled_%s.mat", mappingMode));

save( ...
    outputFile, ...
    "trigger_ts", ...
    "plant_inputs_ts", ...
    "triggerScheduled", ...
    "triggerManual", ...
    "cfg", ...
    "tasks", ...
    "jobsScheduled", ...
    "scheduleScheduled", ...
    "networkLogScheduled", ...
    "mappingMode", ...
    "Ts", ...
    "Tstop", ...
    "-v7.3");

fprintf("Saved scheduled inputs to:\n%s\n", outputFile);